### ISSUE TITLE
Registry port setting

### ISSUE THREAD

**Issue by somppa** [cookbrite/flyingcloud#33]
Trying to build with custom port in host fails 

In flyingcloud.yaml:
```
registry:
  host: "localhost:5000"
```

will give

```
2017-12-21 13:26:25,642 - flyingcloud.base - INFO - Building /home/somppa/flyingcloud/examples/flask-web-app/salt/sysbase/Dockerfile
2017-12-21 13:26:25,642 - flyingcloud.base - INFO - About to build Dockerfile, tag=localhost:5000/cookbrite/flaskexample_sysbase:2017-12-21t112625z
2017-12-21 13:26:25,712 - flyingcloud.base - INFO - Built tag=localhost:5000/cookbrite/flaskexample_sysbase:2017-12-21t112625z, image_id=917363deeabd
2017-12-21 13:26:25,713 - flyingcloud.base - INFO - No salt states found in '/home/somppa/flyingcloud/examples/flask-web-app/salt/sysbase'; not salting.
2017-12-21 13:26:25,713 - flyingcloud.base - INFO - Not squashing layer localhost:5000/cookbrite/flaskexample_sysbase:2017-12-21t112625z
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/somppa/flyingcloud/develop/lib/python2.7/site-packages/flyingcloud/main.py", line 131, in <module>
    main()
  File "/home/somppa/flyingcloud/develop/lib/python2.7/site-packages/flyingcloud/main.py", line 122, in main
    instance.do_operation(namespace)
  File "/home/somppa/flyingcloud/develop/local/lib/python2.7/site-packages/flyingcloud/base.py", line 141, in do_operation
    return method(namespace)
  File "/home/somppa/flyingcloud/develop/local/lib/python2.7/site-packages/flyingcloud/base.py", line 196, in do_build
    self.build(namespace)
  File "/home/somppa/flyingcloud/develop/local/lib/python2.7/site-packages/flyingcloud/base.py", line 256, in build
    self.docker_tag(namespace, layer_strong_name, "latest")
  File "/home/somppa/flyingcloud/develop/local/lib/python2.7/site-packages/flyingcloud/base.py", line 686, in docker_tag
    repo, tag = self.image_name2repo_tag(image_name, tag)
  File "/home/somppa/flyingcloud/develop/local/lib/python2.7/site-packages/flyingcloud/base.py", line 679, in image_name2repo_tag
    repo, image_tag = image_name.split(':')
ValueError: too many values to unpack
```

**Comment by georgevreilly** [comment]
Please provide a callstack. I'm getting a completely different error:
```
docker.errors.APIError: 500 Server Error: Internal Server Error ("Get http://localhost:5000/v2/: dial tcp [::1]:5000: getsockopt: connection refused")
```

Are you really trying to connect to a Docker registry on `localhost:5000`? Or do you want your Docker container to appear in your host at `localhost:5000`? If the latter, then you do this in your `layer.yaml`. See `exposed_ports` in `examples/flask-web-app/salt/app/layer.yaml`.

**Comment by somppa** [comment]
Callstack included to original post.

It appears when you try to build the image with ` flyingcloud -b sysbase`

Registry has no effect if it's running or not.

It works all fine when I put registry to port 80 and remove the port from host setting, building, auto pushing etc
